### ISSUE TITLE
Fix panic when cannot found image

### ISSUE THREAD

**Issue by johnfercher** [johnfercher/maroto#100]
**Describe the bug**
Fix nil pointer in FileImage when cannot found image.

**To Reproduce**
1. Use a FileImage with a wrong path to image.
2. Maroto will panic

**Related code:**
https://github.com/johnfercher/maroto/blob/76210eee05ffeba27b56270d0363ae741093d780/internal/examples/sample1/main.go#L58

**Expected behavior**
Maroto should return error when cannot RegisterImageOptions return nil.
https://github.com/johnfercher/maroto/blob/76210eee05ffeba27b56270d0363ae741093d780/internal/image.go#L33-L36

founded in #99

**Comment by johnferchermeli** [comment]
Fixing in #102

**Comment by johnfercher** [comment]
Fixed.
