### ISSUE TITLE
Migrate from dep to Go module system

### ISSUE THREAD

**Issue by vinicio** [johnfercher/maroto#101]
**Is your feature request related to a problem? Please describe.**
Go's module system, introduced in Go 1.11, is the official dependency management solution built into the go command.

**Comment by johnfercher** [comment]
Hi, I will check this issue.

**Comment by SuddenGunter** [comment]
@johnfercher up for grabs?

**Comment by johnfercher** [comment]
@SuddenGunter, feel free to grap this issue =)

**Comment by johnfercher** [comment]
Fixed in #107
