### ISSUE TITLE
Improve text component

### ISSUE THREAD

**Issue by johnferchermeli** [johnfercher/maroto#106]
**Describe the solution you'd like**
Use markdown syntax to improve text styling, like:

**Describe alternatives you've considered**
Interpret that \*text\* should be *italic*.
Interpret that \*\*text\*\* should be **bold**;
Interpret that \*\*\*text\*\*\* should be ***bold and italic***;
Interpret that \n should break a line in text;

**Additional context**
If this be implemented, I think that props.Text and props.Font shouldn't have the style parameter anymore.

https://github.com/johnfercher/maroto/blob/008f53d6696321151fd2c200347565a36491b9eb/pkg/props/prop.go#L44-L59

https://github.com/johnfercher/maroto/blob/008f53d6696321151fd2c200347565a36491b9eb/pkg/props/prop.go#L61-L69

**Comment by johnferchermeli** [comment]
What do you think about it? @SuddenGunter and @marco-m?

**Comment by marco-m** [comment]
Hello, I see the reasoning. My first thoughts:

* You need to consider what you want to do from an API compatibility point of view. Do you want to offer two functions, one for plain text and one for markdown-like text, or only one, and so markdown always enabled? (I don't have an opinion here, I am only pointing out that a decision must be taken).
* Is there a way to escape the syntax? I mean, is there a way for \*\*foo\*\* to stay as-is ? This seems to be needed.
* If you go down the markdown route, my opinion is that it should be a subset of markdown, never a variation. No funky syntax. This is to follow POLA (Principle Of Least Astonishment) for the user.

**Comment by SuddenGunter** [comment]
agreed with @marco-m points
@johnfercher is there a way to use some calculated values in maroto?
like {pageNumber} or something like that

**Comment by frederikhors** [comment]
Hi guys! Thanks for this awesome pkg!

Can I ask you if this is fixed? I would especially like to find out if this works:

`Interpret that \n should break a line in text;`

Thanks again.
