### ISSUE TITLE
Migrate to Go 1.13 in travis  tests

### ISSUE THREAD

**Issue by SuddenGunter** [johnfercher/maroto#108]
**Is your feature request related to a problem? Please describe.**
2 months as it's out, I think we should adopt it and run all tests against this version so library users had no issues with newer version of Go.

**Describe the solution you'd like**
change line with Go version in travis.yml

**Describe alternatives you've considered**
do not migrate, but I see no issues why don't.

**Comment by BalajiTechs** [comment]
I am trying this

**Comment by BalajiTechs** [comment]
@johnferchermeli  can you help me on how to execute tests on git-bash?

**Comment by SuddenGunter** [comment]
@BalajiTechs if this still relevant, see https://github.com/johnfercher/maroto/blob/master/.travis.yml#L37

**Comment by BalajiTechs** [comment]
> 
> 
> @BalajiTechs if this still relevant, see https://github.com/johnfercher/maroto/blob/master/.travis.yml#L37

Yeah i figured out that script, but somehow not able to test with git-bash. BTW, I managed to upgrade to latest version of Go without local testing(thanks to travis-ci). see https://github.com/johnfercher/maroto/pull/110

**Comment by johnferchermeli** [comment]
Merged
