### ISSUE TITLE
Can't push code to new branch

### ISSUE THREAD

**Issue by Jepzter** [johnfercher/maroto#118]
Hello, Im trying to make contribution to this great repository but only get the following error: 

```
ERROR: Permission to johnfercher/maroto.git denied to Jepzter.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

What do I have to do to contribute?

**Comment by johnfercher** [comment]
Hi, Jepzter. I think you should create a fork from this repository, push your code there and them open a pull request. Have you already tried this?

**Comment by Jepzter** [comment]
Ah, I see! Seems to be working. First time contributing to a public project :)
