### ISSUE TITLE
Add horizontal line after every content-row added

### ISSUE THREAD

**Issue by Jepzter** [johnfercher/maroto#124]
**Is your feature request related to a problem? Please describe.**
Today it's not possible to have a line added after every row added from TableList. This could be useful for separating when having a lot of content.

**Describe the solution you'd like**
Maroto TableList should take a new property called "Line" which is a boolean. The Line should have a default size of 1.0

**Describe alternatives you've considered**

- Create a new property in props.TableList called "Line".
- Check if Line should be added on every content-row looped over.

Additional context

**Comment by johnfercher** [comment]
Merged in to master an released
