### ISSUE TITLE
Bad Layout on Table List with long text

### ISSUE THREAD

**Issue by nmorenor** [johnfercher/maroto#128]
First of all, I like this maroto! Kudos! I'm trying to use it to generate an small pdf of a list and the TableList component looks like a good fit. Although I'm having an odd layout and some of the pages does not even have the registered header, the footer also is not at the bottom of pages.

**To Reproduce**
Try to run the following code: https://gist.github.com/nmorenor/78f0cf3f92e4e22a61ae147deb1357eb

**Expected behavior**
PDF produced, all pages should have a header and footer, when the height of the table list row element is greater than the page size, content go to the next page.

**Comment by johnferchermeli** [comment]
Hey, thank you.

Just a question, are you using the latest version of maroto?

**Comment by johnferchermeli** [comment]
We doesn't support this yet. We will add this to our roadmap.

**Comment by nmorenor** [comment]
Yes, running with the latest version. I'm trying to run this even from the master branch. :)

**Comment by johnfercher** [comment]
This will be addressed in #224 too.
