### ISSUE TITLE
Add a custom page break command

### ISSUE THREAD

**Issue by pyriand3r** [johnfercher/maroto#141]
**Is your feature request related to a problem? Please describe.**
We face the problem, that we need to create a new page in the pdf before the actual page is full. So we need a custom page break command.

**Describe the solution you'd like**
It would be great to be able to tell maroto via command or method call to add a page break at the current position and all content added after the call will be added to a new page.

**Describe alternatives you've considered**
There are no alternatives, as maroto is the only pdf tool i found not using x/y coordinates.

**Additional context**
Maroto is based on/uses gofpdf in the background which allows custom page breaks via the `.AddPage()` method.

**Comment by johnferchermeli** [comment]
Hi @pyriand3r we will add this as soon as possible.

**Comment by elamre** [comment]
Is this feature already implemented?

**Comment by johnferchermeli** [comment]
We have a branch with the feature but is missing the quality proceedings. https://github.com/johnfercher/maroto/tree/feature/add-page
