### ISSUE TITLE
It does not support Chinese and Arabic characters.

### ISSUE THREAD

**Issue by gonzalezlrjesus** [johnfercher/maroto#142]
I needed to create a document in pdf format with texts in different languages ​​(Chinese, Arabic). Although the Text component uses `func (_m *Pdf) UnicodeTranslatorFromDescriptor(cpStr string) func(string) string ` function, it does not support Chinese or Arabic symbols, and converts them to points in the document created.

![image](https://user-images.githubusercontent.com/33332802/78594107-b4baaa80-7815-11ea-9a2c-7d6f88b32392.png)

![image](https://user-images.githubusercontent.com/33332802/78594087-abc9d900-7815-11ea-84b0-359f92ffcabf.png)

**Comment by johnfercher** [comment]
I tried to remove the UnicodeTranslatorFromDescriptor from the Text components but the chinese characters still not working. I found an issue thread on gofpdf that said that gofpdf doesn't support these languages. https://github.com/jung-kurt/gofpdf/issues/59#event-480144997

### Code

```go
m.Col(6, func() {
	m.Text("中文 Packages Report: Daily", props.Text{
		Top:   1,
		Align: consts.Center,
	})
	m.Text("Type: Small, Medium", props.Text{
		Top:   7,
		Align: consts.Center,
	})
})
```

### Result
<img width="359" alt="Captura de Tela 2020-05-16 às 13 54 34" src="https://user-images.githubusercontent.com/4752636/82125522-d7c56c00-977c-11ea-9eba-b0e9563072f2.png">

I don't know another way to add support to these characters.

**Comment by Vale-sail** [comment]
> I tried to remove the UnicodeTranslatorFromDescriptor from the Text component but the chinese characters still not working. I found an issue thread on gofpdf that said that gofpdf doesn't support these languages. [jung-kurt/gofpdf#59 (comment)](https://github.com/jung-kurt/gofpdf/issues/59#event-480144997)
> 
> ### Code
> ```go
> m.Col(6, func() {
> 	m.Text("中文 Packages Report: Daily", props.Text{
> 		Top:   1,
> 		Align: consts.Center,
> 	})
> 	m.Text("Type: Small, Medium", props.Text{
> 		Top:   7,
> 		Align: consts.Center,
> 	})
> })
> ```
> 
> ### Result
> <img alt="Captura de Tela 2020-05-16 às 13 54 34" width="359" src="https://user-images.githubusercontent.com/4752636/82125522-d7c56c00-977c-11ea-9eba-b0e9563072f2.png">
> 
> I don't know another way to add support to these characters.

jung-kurt/gofpdf can use special font to support chinese。
```
gofpdf supports UTF-8 TrueType fonts and “right-to-left” languages. Note that Chinese, Japanese, and Korean characters may not be included in many general purpose fonts. For these languages, a specialized font (for example, NotoSansSC for simplified Chinese) can be used.
```
I solve it. but I donot  use github very well.I donot know how to use pr. 
you can read me code https://github.com/Vale-sail/maroto to get idea. 
if my fork has bad effect for you,please tell us. I will delete my repositories. thank you

**Comment by johnfercher** [comment]
I will open an PR to you

**Comment by hamdiBouhani** [comment]
@johnfercher is there any progress on this issue

**Comment by hamdiBouhani** [comment]
I need to handle Arabic characters in my app
