### ISSUE TITLE
Add accessor to gofpdf

### ISSUE THREAD

**Issue by KramKroc** [johnfercher/maroto#143]
**Is your feature request related to a problem? Please describe.**

The simplicity of the maroto solution is very powerful but sometimes it would be useful to be able to access gofpdf if we wish to do something lower level, i.e. change orientation of a new page etc. What side affects might this cause?

**Describe the solution you'd like**

A documented method of accessing gofpdf. Understand you can "cast" Maroto to PdfMaroto:

```
m := pdf.NewMaroto(consts.Portrait, consts.A4)
var pM = m.(*pdf.PdfMaroto)
pM.Pdf.AddPage()
```
But would there be a "safer" way to do this?

**Describe alternatives you've considered**

Could obviously fork and add needed functionality to do each thing, i.e. add new page with different orientation etc

**Comment by johnfercher** [comment]
I don't think that will work by simply change the orientation directly in gofpdf. There are some calculations that maroto have to do based on the page parameters. Maroto use these parameters to decide when create a new page and what value apply to a column width.

But, we can add a new feature in maroto to change this orientation.

**Comment by johnfercher** [comment]
I saw that we have the #145 issue about your example. I will close this issue an we will follow the another.
