### ISSUE TITLE
Add support to use TrueType UTF-8 encoded fonts

### ISSUE THREAD

**Issue by KramKroc** [johnfercher/maroto#144]
**Is your feature request related to a problem? Please describe.**

Need to produce documents using ttf fonts to match required brand guidelines.

**Describe the solution you'd like**

Ability to add TrueType UTF-8 encoded fonts and refer to it at different points throughout production of document.

**Describe alternatives you've considered**

Use gofpdf directly if it were exposed.

**Comment by johnfercher** [comment]
Do you mean expose AddUTF8Font from gofpdf?
