### ISSUE TITLE
Add custom page size option when creating documents

### ISSUE THREAD

**Issue by sanderaido** [johnfercher/maroto#148]
**Is your feature request related to a problem? Please describe.**
Currently Maroto uses only gofpdf.New to create documents with the few predefined page sizes. (A4, A5, Letter etc.)

**Describe the solution you'd like**
Use gofpdf.NewCustom to allow custom page sizes. Refactor NewMaroto() to accept custom width and height or create a second method for custom documents.

**Comment by johnferchermeli** [comment]
If the only modification is change gofpdf.New to gofpdf.NewCustom, I think that is only copy & paste the maroto.NewMaroto() code, naming the new constructor as maroto.NewCustom() and change the parameters and the called gofpdf constructor.

**Comment by sanderaido** [comment]
I actually created a fork already and am testing the custom layout. Will put up a PR soon!

**Comment by johnferchermeli** [comment]
Very good :D

**Comment by sanderaido** [comment]
I don't know how to update the docs (is it automatic based on example files?) so maybe you can help with that. Otherwise all previous tests still pass and the previous method can be used next to this one.

**Comment by johnferchermeli** [comment]
The docs doesn't have to be updated in every new feature. I will check your PR today =)

**Comment by sanderaido** [comment]
Thanks for the merge! Is there going to be a release soon as well?

**Comment by johnfercher** [comment]
Released :D

**Comment by sanderaido** [comment]
Perfect, thank you!
