### ISSUE TITLE
can i force page break ? Can i specify all margins to be zero  ? thanks for the package.

### ISSUE THREAD

**Issue by birraasmile** [johnfercher/maroto#150]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by birraasmile** [comment]
Good job.

**Comment by johnferchermeli** [comment]
Force page break: https://pkg.go.dev/github.com/johnfercher/maroto/pkg/pdf?tab=doc#PdfMaroto.AddPage

Page Margins: https://pkg.go.dev/github.com/johnfercher/maroto/pkg/pdf?tab=doc#PdfMaroto.SetPageMargins

**Comment by birraasmile** [comment]
Thanks Johnathan.
I should have looked the docs thoroughly,  am sorry :)  Good day.
