### ISSUE TITLE
Output() don't work

### ISSUE THREAD

**Issue by jonathanhecl** [johnfercher/maroto#151]
Output() function don't work, I can't use it.

**Related code:**
```
        // code

        buff, err := m.Output()
	if err != nil {
		fmt.Println("Could not save PDF:", err)
		os.Exit(1)
	}

	fmt.Println(buff.Cap(), buff.Len(), len(buff.String()))
```
_Return_: `0 0 0`

With OutputFileAndClose(..) only works.

**Comment by johnferchermeli** [comment]
I tested here the samples and it's working. Could you provide and example?

**Comment by jonathanhecl** [comment]
`package main

import (
	"fmt"
	"os"

	"github.com/johnfercher/maroto/pkg/consts"
	"github.com/johnfercher/maroto/pkg/pdf"
	"github.com/johnfercher/maroto/pkg/props"
)

func main() {

	m := pdf.NewMaroto(consts.Portrait, consts.A4)
	m.SetPageMargins(10, 10, 140)
	m.SetBorder(true)

	m.Row(5, func() {
		m.Col(12, func() {
			m.Text("Test",
				props.Text{Size: 8, Extrapolate: true, Family: consts.Helvetica, Style: consts.Italic, Align: consts.Right})
		})
	})

	err := m.OutputFileAndClose("zpl.pdf")
	if err != nil {
		fmt.Println("Could not save PDF:", err)
		os.Exit(1)
	}

	buff, err := m.Output()
	if err != nil {
		fmt.Println("Could not save PDF:", err)
		os.Exit(1)
	}

	fmt.Println(buff.Cap(), buff.Len(), len(buff.String()))

}`

**Comment by johnferchermeli** [comment]
Strange, Indeed Outbound doesn't work on your example. But, have you tried to execute only the Outbound without the OutboundFileAndClose? When I did this it worked.
