### ISSUE TITLE
Image for Background

### ISSUE THREAD

**Issue by bimbimprasetyoafif** [johnfercher/maroto#154]
**Is your feature request related to a problem? Please describe.**
I suggest about using image for background. It will help instead using color. 

**Describe the solution you'd like**
Not yet, just suggest. 

**Describe alternatives you've considered**
Maybe could make a prop that can use for backwards the image or just make func to set background from image

**Additional context**
not have

**Comment by Janso123** [comment]
Can we have image for background in config ? 
like : WithBackgroundImage(file string, fitment fitmEntenum) ?

**Comment by johnfercher** [comment]
Add (https://maroto.io/#/v2/features/background?id=add-background)

**Comment by xanderjakeq** [comment]
hi, i am trying to add an image as a background both the size of the pdf and image is 8.5 x 11. 

why does the background not fill the page? i tried adding top margin to push the image down,
but it just makes the img smaller. it seemed like theres a constant bottom margin? and `withmargin` doesn't have an option for it.

marginTop: 0
![image](https://github.com/johnfercher/maroto/assets/13279523/0c855f1a-8bd5-4079-a4fd-0ce0dc28e517)

marginTop: 10
![image](https://github.com/johnfercher/maroto/assets/13279523/73b9acc9-47b8-4487-870e-7ca774adaf77)

is there a way to fix this that i missed?

thanks!
