### ISSUE TITLE
Unicode support is not working properly

### ISSUE THREAD

**Issue by arcanist123** [johnfercher/maroto#155]
**Describe the bug**

When trying to create texts with kirillic letters the output pdf is not showing them. Dots are shown instead
**To Reproduce**
1. build and execute app.go
2.The file will look as attached
**Related code:**
[app.txt](https://github.com/johnfercher/maroto/files/5004248/app.txt)
[somepdf.pdf](https://github.com/johnfercher/maroto/files/5004257/somepdf.pdf)

```
	m.Row(40, func() {
		m.Col(4, func() {
			_ = m.FileImage("D:\\work\\1c\\1c_processors\\go_dev\\123.jpg", props.Rect{
				Center:  true,
				Percent: 80,
			})
		})
		m.Col(4, func() {
			m.Text("Арнидог", props.Text{
				Top:         12,
				Size:        20,
				Extrapolate: true,

			})
			m.Text("очень странные символики", props.Text{
				Size: 12,
				Top:  22,
			})
		})
		m.ColSpace(4)
	})
```

**Expected behavior**
resulting pdf should show kirillic symbols

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: windows 10 home edition
 - Python Version [e.g. `3.5`, `3.6`] n/a

 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

**Comment by frederikhors** [comment]
@arcanist123 me too. Did you find a solution?

**Comment by arcanist123** [comment]
I ended up generating XLSX file instead of PDF

**Comment by voynovia** [comment]
+1

**Comment by johnferchermeli** [comment]
We are adding support to this feature #165.
