### ISSUE TITLE
Page Numbers

### ISSUE THREAD

**Issue by ngudeveloper** [johnfercher/maroto#157]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Is there a way to add page numbers to the footer? Any samples?

**Comment by johnferchermeli** [comment]
Yes, there is a way. You can use the GetCurrentPage inside the Footer closure. We will add this in our example.

https://pkg.go.dev/github.com/johnfercher/maroto@v0.27.0/pkg/pdf#PdfMaroto.GetCurrentPage

**Comment by johnferchermeli** [comment]
Hi, we merged a solution to get the total number of pages to. https://github.com/johnfercher/maroto/pull/159
