### ISSUE TITLE
A method to get the total number of pages?

### ISSUE THREAD

**Issue by frederikhors** [johnfercher/maroto#162]
It would be amazing to have a method to get the total number of pages.

It would be useful to conditionally print something in Header and Footer.

Example:

```go
if m.GetCurrentPage() == m.TotalNumberOfPages() {
  //print "I'm the last one!"
}
```

What do you think about it?

**Comment by johnfercher** [comment]
I don't think this is possible, that's because there is no way to know that is the last page, since you always can add something new. I think this should be handled for the programmer using the lib.
