### ISSUE TITLE
gofpdf' SetCompression() method

### ISSUE THREAD

**Issue by frederikhors** [johnfercher/maroto#168]
In [this issue](https://github.com/jadefox10200/goprint/issues/2#issuecomment-792073678) he says to use the https://github.com/jung-kurt/gofpdf's `SetCompression()` method.

Is there a way to set that compression with Maroto?

Or is Maroto already using it?

Thanks for your invaluable effort!

**Comment by johnfercher** [comment]
Hello, I think we only need to add a method in maroto to call this method in gofpdf. As we did with SetProtection.

https://github.com/johnfercher/maroto/blob/v0.30.0/pkg/pdf/pdf.go#L517
