### ISSUE TITLE
I researched your lib, but don't found an opportunity to work with content on Russian for example. Are you plan to fix that?

### ISSUE THREAD

**Issue by IgorRybak2055** [johnfercher/maroto#177]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by IgorRybak2055** [comment]
I found permanently usage of cp1252, maybe that should be more flexible

**Comment by johnferchermeli** [comment]
Hello, I'm afraid that you have to use a custom utf8 font. As you can see [here](https://github.com/johnfercher/maroto/blob/master/internal/examples/pdfs/utfsample.pdf) there is support for russian content. Also, [here](https://github.com/johnfercher/maroto/blob/master/internal/examples/utfsample/main.go) is an example of how to load a custom utf8 font.
