### ISSUE TITLE
Missing go.sum entries results in errors when importing package

### ISSUE THREAD

**Issue by Joshswooft** [johnfercher/maroto#180]
**Describe the bug**
After importing the module with the command: `go get -u github.com/johnfercher/maroto`
I then tried to run some basic code: 

**Related code:**
```
package main

import (
	"fmt"
	"os"

	"github.com/johnfercher/maroto/pkg/consts"
	"github.com/johnfercher/maroto/pkg/pdf"
)

func main() {
	m := pdf.NewMaroto(consts.Portrait, consts.A4)
	m.SetPageMargins(20, 10, 20)

	err := m.OutputFileAndClose("pdfs/test.pdf")

	if err != nil {
		fmt.Println("⚠️  Could not save PDF:", err)
		os.Exit(1)
	}

	fmt.Println("PDF saved successfully")

}

```

**Expected behavior**
I should be able to import the library without error and the code should save the PDF successfully. 

Note after doing the below `go mod download XXXX` for each error I was able to do solve but it's not ideal when working with the library.

**Stacktrace**
<img width="924" alt="Screenshot 2021-07-05 at 13 27 05" src="https://user-images.githubusercontent.com/60711758/124471662-0e04e700-dd95-11eb-9d90-86599e30160f.png">

**Additional details (please complete the following information):**
 - OS: MacOS
 - Go v1.16

**Comment by johnferchermeli** [comment]
Hello, I will check this. Do you know how to fix this?
