### ISSUE TITLE
Text height calculation

### ISSUE THREAD

**Issue by phillebaba** [johnfercher/maroto#182]
**Is your feature request related to a problem? Please describe.**

Currently if you want to create PDF documents with dynamic content the only solution seems to be using the table list as it will calculate the height for you. It would be nice to be able to get the expected height of text based on font type and size. This would enable more complex document creation that can be created from input with large variation in text amounts.

**Describe the solution you'd like**

Expose a similar function like the one used by table list.
https://github.com/johnfercher/maroto/blob/980cea51f33e5b18b9b3e7669c845874dab50aac/internal/tablelist.go#L119

**Describe alternatives you've considered**

Continue using table list with a single header and column to achieve similar functionality.

**Additional context**

**Comment by johnferchermeli** [comment]
Actually every text have this feature.
