### ISSUE TITLE
TableList without header

### ISSUE THREAD

**Issue by helicoder** [johnfercher/maroto#184]
Is it possible to create a table without the headers?

**Comment by johnferchermeli** [comment]
Hello, I think that is possible. Just pass a empty header.

```golang
header := []string{"", "", "", ...}
```

**Comment by helicoder** [comment]
Yes  it's empty, but still has height. Never mind using grid instead.

In another question how do you pass a reference to m to a function?

This doesn't work, and I can't figure out why

m := pdf.NewMaroto(consts.Portrait, consts.A4)

func PaintBase64ImageRow(m *pdf.PdfMaroto, component models.Component) {

	m.Row(40, func() {
		m.Col(4, func() {
			m.Text(component.Label)
		})
		m.Col(8, func() {
..
.
.
.
.
.
}
