### ISSUE TITLE
Last footer does not draw at bottom

### ISSUE THREAD

**Issue by needsaholiday** [johnfercher/maroto#187]
**Describe the bug**
When applying a footer, the last footer will not be drawn at the bottom.

**To Reproduce**
1. Create a PDF with a footer
2. Add some rows
3. Add page(s)
4. Add 1 Row with size of 10
5. Call `OutputFileAndClose` or `Output`

**Related code:**
```golang
func (s *PdfMaroto) drawLastFooter() {
// ...
}

```

**Expected behavior**
Expected `drawLastFooter()` to fill remaining space like `footer()` does.

I suspect that adding the following block to `drawLastFooter()` solves the issue:

```golang
	totalOffsetY := int(s.offsetY + s.footerHeight)
	maxOffsetPage := int(pageHeight - bottom - top)

	s.Row(float64(maxOffsetPage-totalOffsetY), func() {
		s.ColSpace(12)
	})
```

**Comment by tg-mvooges** [comment]
Could anyone give an update about this bug? We're having the exact same problem. There seems to be a declined pull request? Is this getting fixed, if so: when?

We're about to rewrite our htmlToPdf logic in Go and thusfar this package seems very useful, but this is a mayor problem for us :)

**Comment by johnfercher** [comment]
The PR was rejected because it didn't follow the requirements to merge it, the checklist was ignored. It was opened in 25 Oct 2021 and remained without adequation until 18 Jan 2022. We have intention to fix this.
