### ISSUE TITLE
Clickable text

### ISSUE THREAD

**Issue by milobob** [johnfercher/maroto#191]
I would like to be able to add clickable text 

For example m.Text("www.google.com", props.Text{
					Top:   4,
					Style: consts.Bold,
					Size:  8,
					Align: consts.Left,
                                        URL: "https://www.google.com",
				})

maybe this is already possible but I couldn't figure out how to do it

**Comment by johnfercher** [comment]
The simpler way is to add a link in the cell using `s.pdf.LinkString()` from gofpdf, but maybe we should focus using Cellf in this case.

**Comment by ravi-rigi** [comment]
Hey @johnfercher, is it possible to add link to the text from the Text Props?

**Comment by maxgio92** [comment]
Hi, I guess this issue is completed by #373, isn't it?

**Comment by johnfercher** [comment]
Yes
