### ISSUE TITLE
Text drop shadow property

### ISSUE THREAD

**Issue by SahaPratik6267** [johnfercher/maroto#206]
I am not sure if its already there but i am creating a pdf design that the designer gave and it has a drop shadow property for some text. I want to make the pdf as close to the design as possible so is it possible to add drop shadow on text?

I would also like to know about changing the border design like this 
![image](https://user-images.githubusercontent.com/54626321/165174879-5388a82a-5ff7-4771-893d-f6055756b940.png)

**Comment by johnfercher** [comment]
Hello, I'm afraid that the project which maroto relys on (https://github.com/jung-kurt/gofpdf) doesn't support this kind of feature. So, I see some ways to do implement this, but would take some time.
