### ISSUE TITLE
encoding to cyrillic

### ISSUE THREAD

**Issue by rkBekzat** [johnfercher/maroto#211]
I work with cyrillic script, and when I write some text in cyrillic to my pdf file, I obtrain char ".". 

I found solution for this but it's writtin for  gofpdf library.  Maybe this is already possible in this lib but I couldn't figure out how to do it.

**Comment by johnfercher** [comment]
There are any language which support this [here](https://github.com/johnfercher/maroto/blob/master/internal/examples/pdfs/utfsample.pdf)? If so, I think you only have to use [add an UTF8 font](https://pkg.go.dev/github.com/johnfercher/maroto/pkg/pdf#PdfMaroto.AddUTF8Font) which supports your language, there are an example [here](https://github.com/johnfercher/maroto/blob/master/internal/examples/utfsample/main.go).

**Comment by rkBekzat** [comment]
Yep I tried to solve using add UTF 8 font, actually I had bug in code. I fixed the code and now it's work! Thank you! 
Sorry for bothering.

**Comment by johnfercher** [comment]
Same case as #205
