### ISSUE TITLE
Allow alignment of content in TableListContent on a per column basis

### ISSUE THREAD

**Issue by sazzle2611** [johnfercher/maroto#213]
**Is your feature request related to a problem? Please describe.**
We are currently looking for a pdf generator for all of our projects but a lot of them create invoices and we need to align the amount values like Net, VAT & Total to the right so that they all line up neatly with the decimal point in the same place but we definitely don't want product code and description to be aligned right as this would also be messy

**Describe the solution you'd like**
Allow setting the alighnment per column, maybe something like this (this was actually just the way I tried it before I found out that there was no align on the TableListContent)
```
ContentProp: props.TableListContent{
	Size:      8,
	GridSizes: []uint{3, 7, 2},
	Align:     []consts.Align{consts.Left, consts.Left, consts.Right},
},
```
If Align is not set then just use the one set on the TableList as it does already.

**Describe alternatives you've considered**

**Additional context**

**Comment by johnfercher** [comment]
This may be solved thinking also in this #178 question.

**Comment by Lord-Leonard** [comment]
any update?

**Comment by johnfercher** [comment]
Hello, this will be easy to do in maroto V2. Since you can iterate through a collection of data and build a structure of rows/cols applying all kind of customizations. Please refer to [maroto v2](https://maroto.io/#/v2/examples/billing?id=billing) to see how this can be done. 

Btw, I will keep this issue alive until maroto v2 reaches a stable version.

**Comment by johnfercher** [comment]
I have an update on this. I added a new way to compute tables. The new can be seen here: https://maroto.io/#/v2/features/list?id=list
