### ISSUE TITLE
Possibility to change author, company, keywords and others metadata of a pdf document

### ISSUE THREAD

**Issue by Jeannot-Muller** [johnfercher/maroto#216]
A pdf document has properties. However it seems that you can't edit those yet in Maroto. It would be great to have a possibility to define those when creating a pdf. Thank you for consideration and keep up the excellent work.

**Comment by happsie** [comment]
The [underlying library](https://github.com/jung-kurt/gofpdf) exposes the following properties in it's interface

```
pdf.SetProducer(str, bool)
pdf.SetAuthor(str, bool)
pdf.SetCreator(str, bool)
pdf.SetSubject(str, bool)
pdf.SetTitle(str, bool)
pdf.SetCreationDate(str, bool)
pdf.SetModificationDate(str, bool)
```
Would that be what you're looking for in maroto?
