### ISSUE TITLE
Emoji fallback support

### ISSUE THREAD

**Issue by ModdingFriendly** [johnfercher/maroto#218]
**Is your feature request related to a problem? Please describe.**
When we use the default font, emojis are displayed as □ however, if we use our custom font emojis cause a nil panic. 

**Describe the solution you'd like**
Either dedicated emoji fonts built in or a way to add emoji separate to our normal typeface. 

**Describe alternatives you've considered**
Setting emoji-based fonts as default, this lead to all text being shown as □

**Comment by MAAbdallah** [comment]
Did you find way to render emojis?

**Comment by ModdingFriendly** [comment]
@MAAbdallah nope, still looking into if this will be possible without running chromium locally.

**Comment by danchengash** [comment]
Any solution so far. It crashes on an emoji text

**Comment by johnfercher** [comment]
Does it work if you add a utf8font that have support to emoji?
