### ISSUE TITLE
I have a problem with the font of my language when using func() Text. (Thai Font)

### ISSUE THREAD

**Issue by Yothgewalt** [johnfercher/maroto#219]
I have a problem with The second vowel overlaps with the first vowel in my language.

![Screen Shot 2565-07-31 at 16 12 21](https://user-images.githubusercontent.com/77398391/182021656-75869b2d-6add-4b19-ab09-3318dc511fc4.png)

**Comment by johnfercher** [comment]
Your language also doesn´t have spaces? It the same issue as that #221?

**Comment by johnfercher** [comment]
I think this is an issue with the font which you are using, since maroto works with other languages correctly.
