### ISSUE TITLE
Is the Table auto adjust height not compatible with Chinese？

### ISSUE THREAD

**Issue by donnol** [johnfercher/maroto#221]
**Is your feature request related to a problem? Please describe.**

When I use maroto to generate a pdf contains Chinese, the Table auto adjust height is not work.

I use `NotoSansSC-Regular` font for header, and `SourceHanSansCN-VF` font for content.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![pdf检验报告](https://user-images.githubusercontent.com/5707519/185827121-c43976f6-6b79-4ff5-8e10-17ae428fd862.png)

**Comment by donnol** [comment]
I find the code that split the long content to many parts `words := strings.Split(unicodeText, " ")`
```go
// Add a text inside a cell.
func (s *text) Add(text string, cell Cell, textProp props.Text) {
	s.font.SetFont(textProp.Family, textProp.Style, textProp.Size)

	originalColor := s.font.GetColor()
	s.font.SetColor(textProp.Color)

	// duplicated
	_, _, fontSize := s.font.GetFont()
	fontHeight := fontSize / s.font.GetScaleFactor()

	cell.Y += fontHeight

	// Apply Unicode before calc spaces
	unicodeText := s.textToUnicode(text, textProp)
	stringWidth := s.pdf.GetStringWidth(unicodeText)
	words := strings.Split(unicodeText, " ")
	accumulateOffsetY := 0.0

	// If should add one line
	if stringWidth < cell.Width || textProp.Extrapolate || len(words) == 1 {
		s.addLine(textProp, cell.X, cell.Width, cell.Y, stringWidth, unicodeText)
	} else {
		lines := s.getLines(words, cell.Width)

		for index, line := range lines {
			lineWidth := s.pdf.GetStringWidth(line)
			_, _, fontSize := s.font.GetFont()
			textHeight := fontSize / s.font.GetScaleFactor()

			s.addLine(textProp, cell.X, cell.Width, cell.Y+float64(index)*textHeight+accumulateOffsetY, lineWidth, line)
			accumulateOffsetY += textProp.VerticalPadding
		}
	}

	s.font.SetColor(originalColor)
}

```

**Comment by johnfercher** [comment]
Added a new strategy to break line by using dash instead of space. Added in `v2.0.0-alpha.22` (https://maroto.io/#/v2/features/customfont?id=custom-font)

**Comment by xinyidev** [comment]
Can you add a way that supports both Chinese and English, with spaces or beyond line breaks, which can not only cut letters, but also realize Chinese line breaks?

**Comment by xinyidev** [comment]
> Can you add a way that supports both Chinese and English, with spaces or beyond line breaks, which can not only cut letters, but also realize Chinese line breaks?

@johnfercher

**Comment by johnfercher** [comment]
@xinyidev today is possible to do this with different text components. You can add two texts into one row and apply different strategies in both. But if you want to merge the two texts it will not be possible...
