### ISSUE TITLE
A way to draw lines on Row and Col  

### ISSUE THREAD

**Issue by huriATlunar** [johnfercher/maroto#223]
I wish that I could control which lines to draw on Rows and Cols and just all lines on Row/Col.

**Comment by brunofontes** [comment]
Manually including it as a prop would already work. :)

**Comment by happsie** [comment]
Do you mean draw lines around the actual cell? That should be possible to implement, please verify and I can create a PR

**Comment by brunofontes** [comment]
On my side, yes, so we could customize the way we do in Excel.

For example:  first cell would have only the top and left border, second cell only the top border, etc.
![image](https://github.com/johnfercher/maroto/assets/15826395/e0b5231d-b255-4dfb-8f2f-d992e24caacf)

(Not pretty at all, I know. It is just to illustrate. hahhaha)

Thank you so much!

**Comment by johnfercher** [comment]
Done please refer to: https://maroto.io/#/v2/features/cellstyle?id=cell-style
