### ISSUE TITLE
how to generate pdf with papel continuous 

### ISSUE THREAD

**Issue by jhkim1010** [johnfercher/maroto#227]
I want to generate a pdf in size with a width of 80mm and a continuous height.

can you give me some advice for this?

**Comment by happsie** [comment]
Not sure if this is possible with continous height. However, you can set a custom width and height by using [this function ](https://pkg.go.dev/github.com/johnfercher/maroto/pkg/pdf#NewMarotoCustomSize)

**Comment by johnfercher** [comment]
The solution which @happsie seems to work.
