### ISSUE TITLE
Bulk add of pages via goroutines

### ISSUE THREAD

**Issue by prasangmisra** [johnfercher/maroto#230]
I have a problem statement where I need to create a 500 page pdf, and with the current implementation it happens sequentially.
We can use goroutines to add page objects in parallel and in the end merge those pages in the final pdf. 
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by andresgaviria99** [comment]
Hi @prasangmisra , unfortunately maroto does not have the functionality to write a pdf concurrently, however, you can divide the 500 into 100 send them in go routines generating 5 PDFs of 100 each and then merge with this library -> https://github. com/pdfcpu/pdfcpu , is a possible solution.

**Comment by F-Amaral** [comment]
Hi! This issue is currently under development in Maroto V2 (see Issue #257), a initial version has been implemented in #265 .

**Comment by johnfercher** [comment]
This feature is already implemented in V2. Please refer to [parallelism](https://maroto.io/#/v2/configbuilder?id=parallelism) to use it.
