### ISSUE TITLE
Is it possible to load fonts once?

### ISSUE THREAD

**Issue by joeyave** [johnfercher/maroto#233]
**Is your feature request related to a problem? Please describe.**
Now if I need to load custom fonts I have to do that each time PDF is generated. It takes a lot of memory.

**Describe the solution you'd like**
Function on package level to load fonts once.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by johnfercher** [comment]
## Alternative
Extract Fonts load to functions and keep state on kind of a singleton.

**Comment by johnfercher** [comment]
Added this to `v2.0.0-alpha.21` (https://maroto.io/#/v2/features/customfont?id=custom-font).
