### ISSUE TITLE
Right alignment of total pages

### ISSUE THREAD

**Issue by RaditHP** [johnfercher/maroto#247]
**Function SetAliasNbPages() causes some bugs**
When using this function to get the total pages generated and it is aligned to the right of the column it creates a few whitespaces 

**Current result**
![image](https://github.com/johnfercher/maroto/assets/34481399/cde7d845-716b-4336-a168-9f39948c5945)

**Expected result**

![image](https://github.com/johnfercher/maroto/assets/34481399/6c06a2be-073c-498e-a34f-eeff6b54ef16)

**Related code:**
```
m.Col(8, func() {
		m.Text(lang["ReportTitleHeader"], props.Text{
				Style: consts.Bold,
				Size:  11,
				Align: consts.Right,
			})
			m.SetAliasNbPages("{nbs}")
			paging := fmt.Sprintf("%s %d %s {nbs}", lang["PageDetail"], m.GetCurrentPage()+1, lang["PageHeader"])
			m.Text(paging, props.Text{
				Top:   6,
				Style: consts.Italic,
				Align: consts.Right,
				Size:  9.5,
		})
})
```

Please ignore the different absence of the "Page" string

**Comment by johnfercher** [comment]
V2 is missing page count feature

**Comment by johnfercher** [comment]
Feel free to test (https://maroto.io/#/v2/features/pagenumber?id=pagenumber)
