### ISSUE TITLE
Add Vertical Line

### ISSUE THREAD

**Issue by chiboycalix** [johnfercher/maroto#248]
**Is your feature request related to a problem? Please describe.**
> - I see that I can add horizontal lines to my PDFs but I am not sure I can add Vertical Lines

**Describe the solution you'd like**
> - It should be possible to create vertical Lines and specify a height for them.

**Describe alternatives you've considered**
> - I thought I could use the setBorder method but that did not work for me.

**Additional context**
> - This is a great package and I really enjoy using it so far.

**Comment by johnfercher** [comment]
Hello @chiboycalix, your idea is to add a vertical line inside a row/col?

**Comment by johnfercher** [comment]
Added this to backlog on Maroto V2.

**Comment by johnfercher** [comment]
Added in release `v2.0.0-alpha.20` (https://maroto.io/#/v2/features/line?id=line)
