### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by danchengash** [johnfercher/maroto#251]
**Describe the bug**
The program crashes if a text with an emoji is parsed through the pdf generator

**Expected behavior**
The emoji to be rendered in the output pdf

**Additional context**

**Comment by johnfercher** [comment]
Hey, the charset buildin in maroto/gofpdf don't have emoji support. I think it's possible if you add a custom font that supports emojis. [UTF8 custom font](https://pkg.go.dev/github.com/johnfercher/maroto/pkg/pdf#PdfMaroto.AddUTF8Font)
