### ISSUE TITLE
Some languages don't work

### ISSUE THREAD

**Issue by roms2014** [johnfercher/maroto#252]
**Describe the bug**
Some languages don't work

**To Reproduce**
1. Copy code from https://github.com/johnfercher/maroto/blob/master/internal/examples/utfsample/main.go
2. Compile

**Related code:**
```
https://github.com/johnfercher/maroto/blob/master/internal/examples/utfsample/main.go
```

**Expected behavior**
languages work

**Stacktrace**
no problem

**Additional details (please complete the following information):**
 - OS: Ubuntu
 - Python Version 3.10.12
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**
![Снимок экрана от 2023-08-29 10-42-31](https://github.com/johnfercher/maroto/assets/79161746/e1702dad-aaae-4606-a3ff-21d157a932b4)

**Comment by johnfercher** [comment]
Yes, some languages doesn't work with the charset present inside maroto/gofpdf. To support other languages that have special character that is not inside maroto/gofpdf you have to add an [UTF8 custom font](https://pkg.go.dev/github.com/johnfercher/maroto/pkg/pdf#PdfMaroto.AddUTF8Font) that support it, and there are utf8 fonts that doesn't support all languages too.
