### ISSUE TITLE
Maroto V2 - Thread

### ISSUE THREAD

**Issue by johnfercher** [johnfercher/maroto#257]
Hello, I'm creating this issue to address discussions about the Maroto V2 project.

**Site:** https://maroto.io/
**Main Branch:** [v2](https://github.com/johnfercher/maroto/tree/v2)
**Roadmap:** https://github.com/users/johnfercher/projects/1

**Comment by johnfercher** [comment]
Added @midhunmohan [set metadata methods](https://github.com/users/johnfercher/projects/1/views/1?pane=issue&itemId=39553837)

**Comment by johnfercher** [comment]
@midhunmohan is was added the password. https://maroto.io/#/v2/features/protection?id=protection

**Comment by midhunmohan** [comment]
when using BreakLineStrategy, will there be any option for auto height to the row ? something like dynamically adjusted 

` row.New(4).Add(
			text.NewCol(2, longText, props.Text{Size: 6, Align: align.Center, BreakLineStrategy: breakline.DashStrategy}).WithStyle(colStyle),
		)`

**Comment by johnfercher** [comment]
I tried implement this and we have another try in this pr #302. But it is not that simple. I'm consider to create a function like GetTextHeight() that the users can pass into height value.

**Comment by colearendt** [comment]
Are background color and TableList present in v2 yet? I am having a hard time finding them 😮

**Comment by johnfercher** [comment]
The v2 uses a new approach to do this, you can see in this link: https://maroto.io/#/v2/features/list?id=list

**Comment by pka420** [comment]
Hey guys, just noticed there is no docs on the official go website:

`https://pkg.go.dev/`

I have no idea how to get something published there, but I really like this library and would like to have some docs for each function and type. 

Thanks!

**Comment by colearendt** [comment]
> @colearendt, the v2 uses a new approach to do this, you can see in this link: https://maroto.io/#/v2/features/list?id=list

Thanks! That works great!

Worth noting that I am seeing trouble on your website using Chrome. Works on my phone though

<img width="571" alt="image" src="https://github.com/johnfercher/maroto/assets/23075542/1151d499-347b-415a-aa24-3c6a127b5d58">

It looks like the same approach is what is expected for Border too? Although I cannot seem to get that to work?

```
	shadeColor := &props.Color{
		Red:   238,
		Green: 238,
		Blue:  228,
	}

	blackColor := &props.Color{
		Red:   255,
		Green: 255,
		Blue:  255,
	}
	
	m.AddRows(
		row.New(6).Add(
			col.New(2).Add(),
			col.New(2).Add(text.New("Hi", props.Text{Align: "CM"})).WithStyle(&props.Cell{BorderColor: blackColor, BorderThickness: 10, BorderType: border.Full, LineStyle: linestyle.Solid}),
			col.New(3).Add(text.New("Hi", props.Text{Align: "CM"})),
			col.New(3).Add(text.New("Hi", props.Text{Align: "CM"})),
			col.New(2).Add(),
		).WithStyle(&props.Cell{BackgroundColor: shadeColor, BorderColor: blackColor, BorderThickness: 10, BorderType: border.Full, LineStyle: linestyle.Solid}),
	)
```

**Comment by johnfercher** [comment]
@colearendt could you open an issue about this?

**Comment by colearendt** [comment]
Done! https://github.com/johnfercher/maroto/issues/374

And the website issue, which seems to be Brave related (Chrome proper works fine): #373 

(Although it looks like I have an update available - I will pull that and close if it resolves)

**Comment by johnfercher** [comment]
I will close this because I will create a discussion.
