### ISSUE TITLE
go get url for maroto v2 in docs broken

### ISSUE THREAD

**Issue by aleicher** [johnfercher/maroto#355]
**Describe the bug**

maroto.io docs mention `go get github.com/johnfercher/maroto/v2/pkg@v2.0.0-alpha.41` as install command.

However, this results in no installation of the maroto package, due to the refactoring in the alpha release 33.

**To Reproduce**
Follow the go get command from the documentation

**Expected behavior**
go module is installed after go get

**Additional details (please complete the following information):**
 - OS: MacOS & Linux

**Additional context**
after refactoring the install package no longer exists in /pkg, so proposal is to instead install via `go get github.com/johnfercher/maroto/v2@v2.0.0-alpha.41` which works fine (tested)

**Comment by johnfercher** [comment]
Fixed
