### ISSUE TITLE
concurrent page generation exits the program

### ISSUE THREAD

**Issue by zephyrtronium** [johnfercher/maroto#360]
(*maroto).generateConcurrently contains a call to log.Fatal:

https://github.com/johnfercher/maroto/blob/d697c1320d1d55975d1ee74b929bba8ab4af9b7f/maroto.go#L253-L255

I am experimenting with code running in an AWS Lambda that is hitting this. Because it is log.Fatal in remotely executing code, I have no way to debug the issue or to try to create a reproducer.

It is possibly worth noting that non-concurrent generation succeeds but takes unacceptably long.

**Comment by johnfercher** [comment]
What is the size of the PDF which you are trying to generate?

**Comment by johnfercher** [comment]
I will improve the error handling by exposing better the error cause of which chunk occurred in [go-async](https://github.com/F-Amaral/go-async)

**Comment by johnfercher** [comment]
Created a new release without this `log.Fatal`. I will improve the error handling next.

**Comment by johnfercher** [comment]
You're welcome. How much time the generation to this PDF took in single-core? May you share a printscreen of the content?

**Comment by zephyrtronium** [comment]
Generation took about three minutes in the smallest possible Lambda and about one minute in a larger one with 2 VCPU. The cause of the slowness seems to be some large images being embedded in the document; I downsampled them from 3000×2250 to 640×480 and it completes in a few seconds. Unfortunately I cannot show the PDF content.

**Comment by johnfercher** [comment]
No problem, using large images is really a problem. We are about the introduce a way to manipulate images to avoid this kind of issue.
