### ISSUE TITLE
Maroto Chinese display exception?

### ISSUE THREAD

**Issue by WMMJC** [johnfercher/maroto#366]
I'm having a problem with Maroto, when I set the text to Chinese, it displays ...... It looks like it doesn't support Chinese display
<img width="599" alt="截屏2023-11-07 11 17 53" src="https://github.com/johnfercher/maroto/assets/22298165/6e976682-f03e-4198-af1c-08cb1ecb0c72">
<img width="896" alt="截屏2023-11-07 11 18 24" src="https://github.com/johnfercher/maroto/assets/22298165/8a15d2e9-bdea-4c87-8683-3f1ebf797756">
What should I do to get it to display as normal?

**Comment by woody712** [comment]
same problem

**Comment by johnfercher** [comment]
Hello @WMMJC, as @woody712 said. You have to an a custom utf8 font. Maroto and gofpdf doesn't support utf8 by default. You can see how to do this here: https://maroto.io/#/v2/features/customfont?id=custom-font.
