### ISSUE TITLE
Fix Borders in v2

### ISSUE THREAD

**Issue by colearendt** [johnfercher/maroto#374]
**Describe the bug**

Border styles are not loaded / presented

**To Reproduce**

- build a doc with borders
- notice that borders do not show up

**Related code:**
```
	shadeColor := &props.Color{
		Red:   238,
		Green: 238,
		Blue:  228,
	}

	blackColor := &props.Color{
		Red:   255,
		Green: 255,
		Blue:  255,
	}
	
	m.AddRows(
		row.New(6).Add(
			col.New(2).Add(),
			col.New(2).Add(text.New("Hi", props.Text{Align: "CM"})).WithStyle(&props.Cell{BorderColor: blackColor, BorderThickness: 10, BorderType: border.Full, LineStyle: linestyle.Solid}),
			col.New(3).Add(text.New("Hi", props.Text{Align: "CM"})),
			col.New(3).Add(text.New("Hi", props.Text{Align: "CM"})),
			col.New(2).Add(),
		).WithStyle(&props.Cell{BackgroundColor: shadeColor, BorderColor: blackColor, BorderThickness: 10, BorderType: border.Full, LineStyle: linestyle.Solid}),
	)

```

**Expected behavior**
Show borders

**Stacktrace**
N/A No Errors
**Additional details (please complete the following information):**
 - OS: MacOS

**Additional context**

Discussed briefly in #257

**Comment by johnfercher** [comment]
Hey, I see the problem here. You shade color is almost a white and your black color is actually a white. And you are using a huge border thickness of 10. 

Try to use these values instead and you will see the issue:

```go
shadeColor := &props.Color{
		Red:   255,
		Green: 0,
		Blue:  0,
	}

	blackColor := &props.Color{
		Red:   0,
		Green: 0,
		Blue:  0,
	}

	colStyle2 := &props.Cell{
		BackgroundColor: shadeColor,
		BorderType:      border.Full,
		BorderColor:     blackColor,
		LineStyle:       linestyle.Solid,
		BorderThickness: 0.5,
	}

```

**Comment by colearendt** [comment]
Welp. That's a big ol' goof 🤣 

Thanks for your patience! It is working fantastic, thanks!

<img width="899" alt="image" src="https://github.com/johnfercher/maroto/assets/23075542/af1047ff-9133-48b8-9d51-e7bf5d353143">
