### ISSUE TITLE
Race condition error in header during parallel rendering

### ISSUE THREAD

**Issue by FelipeCooper** [johnfercher/maroto#378]
**Describe the bug**

Hello,

I'm encountering an issue when rendering pages using goroutines in my project. The problem is related to a race condition that occurs in the following file:
https://github.com/johnfercher/maroto/blob/09b0b841e3e56a6d2d861a027847afa3b11e65d5/pkg/props/text.go#L84

The race condition happens when we use the RegisterHeaders function, which registers a header propagated to all pages, https://github.com/johnfercher/maroto/blob/09b0b841e3e56a6d2d861a027847afa3b11e65d5/maroto.go#L75
https://github.com/johnfercher/maroto/blob/09b0b841e3e56a6d2d861a027847afa3b11e65d5/maroto.go#L173
since each goroutine is rendering a page, the state of the component is being altered in one function while another is trying to access it, resulting in an error.

**To Reproduce**
Using this code snippet, it is possible to simulate the error:

```go
func main() {
	cfg := config.NewBuilder().
		WithWorkerPoolSize(5).
		Build()
	m := maroto.New(cfg)
	m.RegisterHeader(
		text.NewRow(0, "header", props.Text{
			Left: 150,
		}))
	m.AddPages(
		page.New().Add(row.New(20).Add(col.New(12))),
		page.New().Add(row.New(20).Add(col.New(12))))
	m.Generate()
}
```

```go 
func TestRaceCondition(t *testing.T) {
	main()
}
```

```shell
 go test ./... -race
```

**Expected behavior**
The test should not fail.

**Stacktrace**
```
WARNING: DATA RACE
Read at 0x00c00027c5d8 by goroutine 10:
  github.com/johnfercher/maroto/v2/pkg/props.(*Text).MakeValid()
      /Users/mcooper/go/pkg/mod/github.com/johnfercher/maroto/v2@v2.0.0-beta.4/pkg/props/text.go:92 +0xb4
  github.com/johnfercher/maroto/v2/pkg/components/text.(*text).Render()
      /Users/mcooper/go/pkg/mod/github.com/johnfercher/maroto/v2@v2.0.0-beta.4/pkg/components/text/text.go:56 +0x6c
  github.com/johnfercher/maroto/v2/pkg/components/col.(*col).Render()
      /Users/mcooper/go/pkg/mod/github.com/johnfercher/maroto/v2@v2.0.0-beta.4/pkg/components/col/col.go:71 +0x154
  github.com/johnfercher/maroto/v2/pkg/components/row.(*row).Render()
      /Users/mcooper/go/pkg/mod/github.com/johnfercher/maroto/v2@v2.0.0-beta.4/pkg/components/row/row.go:77 +0x1cc
  github.com/johnfercher/maroto/v2/pkg/components/page.(*page).Render()
      /Users/mcooper/go/pkg/mod/github.com/johnfercher/maroto/v2@v2.0.0-beta.4/pkg/components/page/page.go:40 +0x388
  github.com/johnfercher/maroto/v2.(*maroto).processPage()
      /Users/mcooper/go/pkg/mod/github.com/johnfercher/maroto/v2@v2.0.0-beta.4/maroto.go:275 +0x1cc
  github.com/johnfercher/maroto/v2.(*maroto).processPage-fm()
      <autogenerated>:1 +0x4c
  github.com/f-amaral/go-async/pool.NewPool[go.shape.[]github.com/johnfercher/maroto/v2/pkg/core.Page,go.shape.[]uint8].func1()
      /Users/mcooper/go/pkg/mod/github.com/f-amaral/go-async@v0.3.0/pool/jobpool.go:32 +0x88
```
**Additional details (please complete the following information):**
 - OS: MacOS
 - Python Version 3.11.5
 - v2.0.0-beta.4

**Comment by johnfercher** [comment]
Hello, this occurs when you runs the code or is just when you runs a test to analyze race conditions?

**Comment by johnfercher** [comment]
Could you test this on the newest version?

```
go get github.com/johnfercher/maroto/v2@v2.0.0-beta.6
```

**Comment by FelipeCooper** [comment]
> Could you test this on the newest version?
> 
> ```
> go get github.com/johnfercher/maroto/v2@v2.0.0-beta.6
> ```

Hi John, the fix in https://github.com/johnfercher/maroto/pull/379 has resolved the issue. The race condition error is no longer present. Thanks :)
