### ISSUE TITLE
image.NewFromFileCol fails to parse jpeg image

### ISSUE THREAD

**Issue by pierrejoye** [johnfercher/maroto#382]
**Describe the bug**
image.NewFromFileCol(4, "happy hour.jpeg") fails to parse jpeg images (multiple files, same errors).
Using image.NewFromBytesCol works.

**To Reproduce**

Using the https://maroto.io/#/v2/examples/simplest?id=simplest example as a repro.

**Related code:**

https://maroto.io/#/v2/examples/simplest?id=simplest

I replaced the plane jpeg with other files. Parse errors.

![happy hour](https://github.com/johnfercher/maroto/assets/282408/3478ec83-3be7-4178-8198-a1d50e67ac6c)

**Expected behavior**

**Stacktrace**

**Additional details (please complete the following information):**
Windows 11 Pro 22631.2861

I suspect it may be in fpdf as I could not find any error in Maroto, it passes the right image type all the way down (to the Cache and below).  I did not debug the deps yet, I worked around it by loading into []byte and use NewFromBytesCol instead.

Repro using v2.0.0-beta.7 and current  master.

**Additional context**

**Comment by johnfercher** [comment]
Hello, issue fixed on https://github.com/johnfercher/maroto/releases/tag/v2.0.0-beta.9
