### ISSUE TITLE
Add Line spacing in text Component

### ISSUE THREAD

**Issue by Thibault-Van-Win** [johnfercher/maroto#385]
**Is your feature request related to a problem? Please describe.**
I am generating a PDF with custom font and don't see a way to provide line spacing. Now, some lines are too close to each other to read them comfortably.

**Describe the solution you'd like**
Provide an option to set line space distance

**Describe alternatives you've considered**
Implement own line splitting on top and construct text as multiple rows, each containing one rule. Setting the height of this row implicitly sets the line spacing. I was wondering if there is a better option to accomplish this.

**Additional context**
Picture to visualise the problem with Open Sans:
![image](https://github.com/johnfercher/maroto/assets/70701521/3bbbafef-77bb-4b4d-aff6-6b6514eb4449)

**Comment by johnfercher** [comment]
Hello, are you using v2?

**Comment by Thibault-Van-Win** [comment]
Yes, this was generated with v2

**Comment by johnfercher** [comment]
Does VerticalPadding work?

**Comment by johnfercher** [comment]
I tried VerticalPadding and seems to work.

![image](https://github.com/johnfercher/maroto/assets/4752636/fffb3f4a-0057-487a-a8f5-1455b00c3c34)

**Comment by Thibault-Van-Win** [comment]
Yes this does the job, can't believe i have missed this. Thanks!
