### ISSUE TITLE
EAN barcode encoding

### ISSUE THREAD

**Issue by nando35x** [johnfercher/maroto#399]
can you add a way to set EAN encoding to barcode please 😄

**Comment by johnfercher** [comment]
Hello, could you validate if these last barcodes are EAN? https://github.com/johnfercher/maroto/blob/feature/new-barcodes/docs/assets/pdf/barcodegridv2.pdf

![Screenshot from 2024-02-21 19-02-27](https://github.com/johnfercher/maroto/assets/4752636/9cfa5e7a-7e38-42a3-8842-e6fbc37a16e6)

**Comment by johnfercher** [comment]
So I will consider the issue solved :D
