### ISSUE TITLE
Multiline text with indentation

### ISSUE THREAD

**Issue by Enkh99** [johnfercher/maroto#400]
**Is your feature request related to a problem? Please describe.**
I need text-indentation in props.Text opts.

**Describe alternatives you've considered**
 It can be hacked if there is only 1 line text, but in my case there will be multi-line text like paragraph. 

**Additional context**
In textgrid/v2/main.go file, there is line which mentionedissue that im facing, but there is no example of it

	m.AddRows(text.NewRow(10, "Multiline text with indentation"))

**Comment by Fernando-hub527** [comment]
Hello!
I'm trying to help solve the problem, but I don't know if I understood correctly. In the example in the photo, I adjusted the distance of the paragraph from the margin and made a small indentation in the first line of the paragraph. Do you need to do something like this or did I make a mistake?

![Captura de tela de 2024-03-22 23-37-11](https://github.com/johnfercher/maroto/assets/66834579/f2e36385-7dbc-4a99-a847-0153a49c4a01)

**Comment by Fernando-hub527** [comment]
Excellent ! 
To do it this way I used the alignment and margin properties of "props.Text" and to indent the first line I added a space at the beginning of the text. Do you think this is a good solution or is it better to do it another way?
