### ISSUE TITLE
Drawing a box or support for nested rows

### ISSUE THREAD

**Issue by midhunmohan** [johnfercher/maroto#405]
Is ther any way like we can draw a box and inside of which rows and cols can be added?

for eg:

> Outer Row with Border-Full
>> Row1
>> Row2
>> Row3

**Comment by midhunmohan** [comment]
![image](https://github.com/johnfercher/maroto/assets/15339404/d49fd9fc-6aca-4782-b23e-a5efd32bf184)
 my requirement is omething like this, any luck for this?

**Comment by johnfercher** [comment]
The outer border yes, the circle border no.

**Comment by midhunmohan** [comment]
if possible can you share a layout for the same

**Comment by johnfercher** [comment]
These would be one line with 2 columns. The first column may have size 4, the second column may have size 8. The image will have to have a circle shape with white background and will have be in first column. The second column you will add some texts and place them manually.

**Comment by midhunmohan** [comment]
worked thanks
