### ISSUE TITLE
Add support for watermarks

### ISSUE THREAD

**Issue by jpuriol** [johnfercher/maroto#410]
**Is your feature request related to a problem? Please describe.**
I have a program that generates PDFs with schedules using this library. Once they are generated I distribute it to check that everyone is aware for the scheles the have. Usually a have to generate a second version with adjustments. I will like that first version to have a watermark that says "temporary" so definitive schedule isn't mistaken by the first one.

**Describe the solution you'd like**
I would like to generate PDF with watermarks using this library

**Comment by johnfercher** [comment]
You can define a background image (https://maroto.io/#/v2/features/background?id=add-background)

**Comment by johnfercher** [comment]
Since there is no response after 1 month, I will assume that background worked to this case.
