### ISSUE TITLE
Custom Font or styling for Footer Page numbers Section

### ISSUE THREAD

**Issue by midhunmohan** [johnfercher/maroto#412]
Is there any way we can edit font styles for page number.

```go	
cfg := config.NewBuilder().
		WithPageNumber("Page {current} of {total}", props.RightBottom).
		WithMargins(10, 5, 10).Build()
```

or  we can get current page number so that we can give it as part of `RegisterFooter`

**Comment by johnfercher** [comment]
Current there is no way. We can create a props.PageNumber with all fields from props.Font and props.Position.
