### ISSUE TITLE
Low quality QR codes

### ISSUE THREAD

**Issue by ianzren** [johnfercher/maroto#413]
**Describe the bug**
Not sure if this is a bug or intended but noticed that the generated QR code is of much lower quality than the example in the docs. I ran the "simplest" example given locally which produced this pdf.

![image](https://github.com/johnfercher/maroto/assets/56396949/ee545ff7-aa46-4639-8883-fbf1324e1ef2)

Docs

![image](https://github.com/johnfercher/maroto/assets/56396949/d16d333e-4e56-4ea5-8742-67b6d260b592)

The generated PDF looks high quality in Chrome and Firefox but low quality in Safari. Physically printing the PDF also always returns a low quality qr code.

Simplest example code

```
func main() {
	m := GetMaroto()
	document, err := m.Generate()
	if err != nil {
		log.Fatal(err)
	}

	err = document.Save("./cmd/ian/ian.pdf")
	if err != nil {
		log.Fatal(err)
	}
}

func GetMaroto() core.Maroto {
	m := maroto.New()

	m.AddRow(20,
		code.NewBarCol(4, "barcode"),
		code.NewMatrixCol(4, "matrixcode"),
		code.NewQrCol(4, "qrcode"),
	)

	m.AddRow(10, col.New(12))

	m.AddRow(20,
		image.NewFromFileCol(4, "docs/assets/images/biplane.jpg"),
		signature.NewCol(4, "signature"),
		text.NewCol(4, "text"),
	)

	m.AddRow(10, col.New(12))

	m.AddRow(20, line.NewCol(12))

	return m
}
```

**Comment by johnfercher** [comment]
I don't know what this can be. But I know that there are printed codes that are in good quality, since maroto is used in production envs world wide.

**Comment by Fernando-hub527** [comment]
I don't know if this is relevant information, but testing in the Debiam document viewer, I had the same result as you, but when zooming in on the image the quality seems to have remained as in the example in the documentation, this low quality is not related to some configuration in the pdf reader?
Unfortunately I don't have access to a printer or safari to validate this possibility.

**Comment by johnfercher** [comment]
Since there is no response after 2 weeks, and we know that the QRCodes and Barcodes are working in other platforms I will close this.

**Comment by renom** [comment]
I have the same problem.
QR codes are blurred in some PDF viewers, meanwhile in other apps they're displayed in good quality.

**Comment by renom** [comment]
It looks like QR code is a low resolution image, where each dot is a single pixel so that it's getting upscaled in the document.
I figured it out by saving the QR code as an image from the PDF viewer.

**Comment by renom** [comment]
https://superuser.com/a/372157
It seems some PDF viewers don't respect `Interpolate` flag (which is `false` by default).
Probably it's the cause of blurred images after upscaling.
Any ideas how to work around this? Maybe it's possible to upscale barcode during PDF generation? (to avoid upscaling images in PDF viewers)

**Comment by renom** [comment]
Well, it seems downscaling from a highly "oversized" image is also an option.
I upscaled a barcode with `libBarcode.Scale(qrCode, 990, 990)` and it looks almost the same as upscaled with a viewer that respects `Interpolate=false`. It's a little bit different though, the dots are a little bit thicker, maybe still slightly blurry. But my phone camera scans it fine.

Another idea from the internet: using vector images could also solve the problem.
