### ISSUE TITLE
Changing font on the go

### ISSUE THREAD

**Issue by lordofscripts** [johnfercher/maroto#417]
What if I am outputting a paragraph of text and then say I want to switch the font to **Courier** to output some code, and then revert back to plain text formatting?

There seems to be a `Font` structure with style & family, but there is no New function and I see other font related stuff spread in various namespaces. I can use `Font{}` as is to construct the instance, but I wonder if perhaps that's not the way it's meant to be used in this framework.

I am thus _confused as to what would be the proper way to switch fonts in Maroto v2?_

**Comment by johnfercher** [comment]
Thanks for your issue, but since this is duplicated I will close an keep only #189.
