### ISSUE TITLE
Tip on creating table with row span

### ISSUE THREAD

**Issue by akissa** [johnfercher/maroto#434]
Hi

Is it possible to create a table like this one given columns do not accept
rows in them.

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Address</th>
      <th>Count</th>
      <th>Volume</th>
      <th></th>
    </tr>
  </thead>
  <tr>
    <td>1</td>
    <td>xxxxxx</td>
    <td>200</td>
    <td>1MB</td>
    <td rowspan="5">Pie chart img</td>
  </tr>
  <tr>
    <td>2</td>
    <td>xxxxxx</td>
    <td>10</td>
    <td>1KB</td>
  </tr>
  <tr>
    <td>3</td>
    <td>xxxxxx</td>
    <td>10</td>
    <td>1KB</td>
  </tr>
  <tr>
    <td>4</td>
    <td>xxxxxx</td>
    <td>10</td>
    <td>1KB</td>
  </tr>
  <tr>
    <td>5</td>
    <td>xxxxxx</td>
    <td>10</td>
    <td>1KB</td>
  </tr>
  <tbody>
  </tbody>
</table>

**Comment by johnfercher** [comment]
Thank you for the issue, I will close it as we already have another one.
