### ISSUE TITLE
Need to know grid size when other than 12

### ISSUE THREAD

**Issue by lordofscripts** [johnfercher/maroto#438]
We know that:

- The standard grid is 12 columns wide,
- That `Maroto` allows to extend that grid to other values, for example 20.

As we build our document we sometimes need to find out if the current `Row` already has the maximum span.

The issue here is that if the user program is using, via Maroto, a grid size other than 12, we have no way of retrieving that via the `core.maroto` object. _It is a write-only property missing a read accessor_.

That API method is rather easy to implement. There is little point in allowing to change the grid size if other parts of the program cannot query it to act accordingly.

**Comment by Fernando-hub527** [comment]
Hello!
I agree that it is simple. In this case, I believe it would be interesting to create a method that makes the entire object [config](https://github.com/johnfercher/maroto/blob/master/maroto.go) available, so it would be possible to recover the size of the grid and other configuration variables, what do you think?

**Comment by lordofscripts** [comment]
That would work for me 👍
