### ISSUE TITLE
Signature text is not aligned

### ISSUE THREAD

**Issue by lordofscripts** [johnfercher/maroto#448]
**Describe the bug**
The signature component is made up of a `Line` with underneath the signature text.

One would expect that signature text to be centered, or at least left-justified underneath the signature's "_sign here_" line. However, I noticed that it is right justified in some cases (unusual) or something that is neither left, nor middle, nor right-justified.

**To Reproduce**
Assuming a standard column span of 12, first do a row with a single signature with the first 3 columns for the signature and the rest empty.

Then do the same with THREE signatures on the same row, allowing 3 columns for the signature and 1 column as spacer in between signatures, so 3+1+3+1+3+1.

**Related code:**

**Expected behavior**
The usual in a document would be that the signature's "typed" text be centered underneath the line. If not, at least left-justified.

**Stacktrace**
N.A.

**Additional details (please complete the following information):**
 - OS: Linux/Debian
 - Python Version 3.9
 - Maroto v2.0.7

**Additional context**
N.A.

**Comment by johnfercher** [comment]
This seems centralized to me.

```go
m.AddRow(40,
		signature.NewCol(3, "Signature 1"),
		signature.NewCol(1, "Signature 2"),
		signature.NewCol(3, "Signature 3"),
		signature.NewCol(1, "Signature 4"),
		signature.NewCol(3, "Signature 5"),
		signature.NewCol(1, "Signature 6"),
	)
```

![Screenshot from 2024-08-03 15-49-52](https://github.com/user-attachments/assets/e9141163-16d9-4a66-9cca-d3a94a156237)

**Comment by johnfercher** [comment]
```go
m.AddRow(40,
		signature.NewCol(3, "Signature 1"),
		col.New(1),
		signature.NewCol(3, "Signature 3"),
		col.New(1),
		signature.NewCol(3, "Signature 5"),
		col.New(1),
	)
```

![Screenshot from 2024-08-03 15-51-56](https://github.com/user-attachments/assets/994874c1-4abf-410f-a3be-5305a4f01d19)

They are centralized in the cell which is create by a col inside a row.

**Comment by johnfercher** [comment]
If you want to centralized the 3 signatures in the page in this way. You can change the MaxGridSum to 13 instead of 12.

```go
	cfg := config.NewBuilder().
		WithMaxGridSize(13).
		Build()

	m := maroto.New(cfg)

	m.AddRow(40,
		col.New(1),
		signature.NewCol(3, "Signature 1"),
		col.New(1),
		signature.NewCol(3, "Signature 3"),
		col.New(1),
		signature.NewCol(3, "Signature 5"),
		col.New(1),
	)
```

![Screenshot from 2024-08-03 15-54-33](https://github.com/user-attachments/assets/0265542f-7b1e-4f4e-8961-69d44e530884)

**Comment by johnfercher** [comment]
If you want to increase the signature length, you can increase even more the MaxGridSum

```go
	cfg := config.NewBuilder().
		WithMaxGridSize(22).
		Build()

	m := maroto.New(cfg)

	m.AddRow(40,
		col.New(1),
		signature.NewCol(3, "Signature 1"),
		col.New(1),
		signature.NewCol(3, "Signature 3"),
		col.New(1),
		signature.NewCol(3, "Signature 5"),
		col.New(1),
	)
```


![Screenshot from 2024-08-03 15-58-33](https://github.com/user-attachments/assets/f036348b-3fec-4b08-81cb-ad58513ffc5e)
