### ISSUE TITLE
Paragraphs on a row isn't working

### ISSUE THREAD

**Issue by lordofscripts** [johnfercher/maroto#450]
**Describe the bug**
When I feed a whole paragraph to a row then the output shows a mess of text printed on top of each line.

Basically, you don't know how many lines it will use and the issue is the necessity of specifying Row Height rather than letting the engine figure it out.

**To Reproduce**
1. Make a **big** paragraph text in a string and place it in a text component.
2. Add that text component to a Column
3. Add that column to a row
4. Generate document

**Related code:**

**Expected behavior**
Paragraph split into lines and lines printed sequentially appearing one after the other in the printed document, as opposed to printing multiple lines on top of each other.

We work with dynamic text and `Maroto` forces the developer to guess the row height. _What works in one situation doesn't work in another_.

At present, `Maroto/v2` is suited for formulaic text, forms but not real life prose.

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: [e.g. MacOS, Ubuntu, CentOS]
 - Python Version [e.g. `3.5`, `3.6`]
 - `HEAD` Commit hash [e.g. `4629c62`]

**Additional context**

**Comment by Fernando-hub527** [comment]
Hello, I did some tests and had the same result: when adding more than one line with a paragraph in each, the text overlaps. As you said, this is likely related to the fact that the line height is not taken automatically.

I did some tests and got the line height to be taken automatically when the content is text:

![Captura de tela de 2024-06-08 18-03-21](https://github.com/johnfercher/maroto/assets/66834579/027e51b3-4af4-4b54-9179-783cce7fb60c)
![Captura de tela de 2024-06-08 18-03-50](https://github.com/johnfercher/maroto/assets/66834579/a8f44d5d-056a-4354-bc0b-024ab79ffed1)

See that although the line height is zero, it is recalculated when generating the pdf, do you think this solution solves it?

My suggestion is that in the Row's Render method the height of the row content is calculated, this implies that Col and the components need to have a GetHeight method, in addition if it is done this way the row height will only be calculated in the render, which will make it difficult to implement the Row's GetHeight method.
I can work on implementing the solution, but first it's interesting to know if this is the best way to solve the problem.
@johnfercher

**Comment by lordofscripts** [comment]
Interesting solution (workaround?). Let me try it tomorrow when I am back at the computer. I too was using an embedded Lorem Ipsum as paragraph text.

**Comment by lordofscripts** [comment]
@johnfercher Tried it but I am not getting such result. While the long Lorem Ipsum paragraph text is now flowing down, I see my other text outputs overlapping the Lorem Ipsum paragraphs as if those paragraphs were a background.

Basically, I am trying to produce a document. For that I am trying to have the following primitives:

- Title
- Subtitle
- Text line
- Paragraph
- Headings (H1, H2... H5)
- forced Line breaks

During initialization I create default styles such as _Title, Subtitle, H1..H5, PlainText, Code_. Those _styles_ are converted to a `Maroto`  instance of `props.Text`. In the following code assume `mary` is a Maroto instance.

```
func Heading1(heading string) {
   var cellS props.Text = getTextStyle(StyleH1)
   mary.AddRows( text.NewRow(0, heading, cellS) )
}

func Heading2(heading string) {
   var cellS props.Text = getTextStyle(StyleH3)
   mary.AddRows( text.NewRow(0, heading, cellS) )
}

func Heading3(heading string) {
   var cellS props.Text = getTextStyle(StyleH2)
   mary.AddRows( text.NewRow(0, heading, cellS) )
}

func Paragraph(texto string) {
    mary.AddRows( text.NewRow(0, texto) )
    LineBreak()
}

func HorizontalRule() {   // <--- not quite working...
    opts := props.Line{
      Color: &ColorIndigo,
      Thickness: 0.4,
      SizePercent: 90.0,
    }
    mary.AddRows(line.NewRow(6, opts)
}

func LineBreak() {    // <---- this is not working either
     mary.AddRows( text.NewRow(0, "\n") )
}
```

So, if I do this, the Paragraph text appears in the background while _the other text overlaps it_.

```
func test() {
    Heading1("I. Chapter 1")
    Paragraph(LoremIpsum)

    Heading2("1.2 Subsection")
    Paragraph(LoremIpsum)

    Heading3("1.2.1 Another Subsection")
    Text("Just a line of text")
    HorizontalRule()

}
```

**Comment by Fernando-hub527** [comment]
> Solução interessante (solução alternativa?). Deixe-me tentar amanhã, quando voltar ao computador. Eu também estava usando um Lorem Ipsum incorporado como texto de parágrafo.

hello
It's an idea of ​​how to add this feature to the lib, I made some changes to Maroto's code to test whether it would be difficult to make the Row's height automatically calculated based on its content. My suggestion is to implement the solution I described in Maroto so that it already does this automatic calculation, but first I think it's important to check if this is the best way to add this feature

**Comment by lordofscripts** [comment]
> It's an idea of ​​how to add this feature to the lib, I made some changes to Maroto's code to test whether it would be difficult to make the Row's height automatically calculated based on its content. My suggestion is to implement the solution I described in Maroto so that it already does this automatic calculation, but first I think it's important to check if this is the best way to add this feature

So, this example you posted doesn't actually work in 2.0.7, right? That's why I cannot get it to work.

**Comment by lordofscripts** [comment]
->@Fernando-hub527 any progress on this? I see there have been two patches (2.0.7 -> 2.0.9) but no mention of this.

**Comment by Fernando-hub527** [comment]
> ->@Fernando-hub527algum progresso nisso? Vejo que houve dois patches (2.0.7 -> 2.0.9), mas nenhuma menção a isso.

I had a little difficulty implementing the feature when the line content is an image, so I only finished the implementation today, I need to do some examples and tests, but I'll try to open the pr today or tomorrow

**Comment by Fernando-hub527** [comment]
Hello, sorry for the delay, but this feature was a little difficult. The pr is open, I believe it will be available soon
