### ISSUE TITLE
Windows-1250 charset support (Czech language)

### ISSUE THREAD

**Issue by ni3mm4nd** [johnfercher/maroto#451]
**Describe the bug**

**To Reproduce**
1. Characters like "ě", "č", "ř" etc. are not supported

**Expected behavior**
Show all UTF-8 characters

**Additional details (please complete the following information):**
 - OS: MacOS

**Additional context**
<img width="1027" alt="image" src="https://github.com/johnfercher/maroto/assets/13623907/0c9c3594-7d12-44ce-a4c2-40e237a5666e">

**Comment by johnfercher** [comment]
Maroto doesn't have UTF8 font embedded, you have to download one, load and use in maroto. As you can se here: https://maroto.io/#/v2/features/customfont?id=custom-font
