### ISSUE TITLE
Underline Text Support

### ISSUE THREAD

**Issue by ldmtam** [johnfercher/maroto#463]
Currently, Maroto supports various text formatting options but lacks native support for underlining text. This feature would improve text styling flexibility.

**Comment by Fernando-hub527** [comment]
Hello, I believe that underlining the text will not be a problem (I think gofpdf supports underlining) but as it will only be necessary to underline a few words, I think it will be necessary to divide the text into subtexts and make each one have its own style properties , including the underline. I **think** that when this pr(#447) is finished it won't be very difficult to implement this.
