### ISSUE TITLE
Vertical alignment of text fields not working?

### ISSUE THREAD

**Issue by mmarvb8h** [johnfercher/maroto#468]
**Describe the bug**

Using v2. I have been unable to get vertical alignment to work.

**To Reproduce**

Using the below code.

**Related code:**
```
	line := row.New(40).Add(
		text.NewCol(
			3,
			"Testx2 Dummy",
			props.Text{
				Size:  12,
				Align: align.Bottom,
			},
		),
	)
	line.WithStyle(&props.Cell{
		BackgroundColor: &props.Color{Red: 200, Green: 200, Blue: 200},
	})
```

**Expected behavior**

I expect the following to be aligned at the bottom not the top which apears to be the default.

![image](https://github.com/user-attachments/assets/dd8f8880-b3ef-4cc3-959c-3b33cb024980)

**Stacktrace**

**Additional details (please complete the following information):**
 - OS: MacOS
 
**Additional context**

Marvin Foster - mmarvb7@gmail.com

**Comment by johnfercher** [comment]
Duplicated #457
