### ISSUE TITLE
"could not add image to document" for a png

### ISSUE THREAD

**Issue by nikolai-shilin** [johnfercher/maroto#470]
**Describe the bug**
Receiving a message "could not add image to document" for a png file. 
What can cause it?

**Related code:**
```
if stampedSignatureFilename != "" {
		pdf.P.Add(row.New(40).Add(
			text.
				NewCol(1, ""),
			image.NewFromFileCol(sw, IMAGE_FOLDER+stampedSignatureFilename, props.Rect{
				Center:  true,
				Percent: 100,
				Top:     1,
			}),
		).
			WithStyle(&pdf.CellDefault))
	}
```

**Expected behavior**
An image is shown

MacOS+Ubuntu

**Comment by johnfercher** [comment]
Is possible that the file is not being found in the directory. Try to use `os.ReadFile`, this may also fail to load.
