### ISSUE TITLE
Nil pointer when getting column height on Register Header

### ISSUE THREAD

**Issue by anabarbaraseabra** [johnfercher/maroto#473]
**Describe the bug**

Hello, I am updating the version of Maroto from V1 to V2 and encountered an issue right at the beginning of the process of adding information that will make up the PDF, specifically when using the **_**RegisterHeader**_** method.

At a certain point in this method, when getting the column height using the _**GetSize**_ method, the config attribute of the column is not being initialized, resulting in a Nil Pointer error.

I am using the method as shown in the snippet below, and upon debugging, I noticed that the **_config_** attribute is Nil for all the columns in the row:

```
_ = m.RegisterHeader(
	b.getLogoRowBySiteID(report.SiteId),
	b.getBarcodeRow(report.Code),
	line.NewRow(3, props.Line{
		Style:       linestyle.Solid,
		SizePercent: 100,
		Thickness:   0.3}))
```

This behavior starts happening on version v.2.1.0

**Comment by Fernando-hub527** [comment]
Hello!
I believe I can help with this issue, but I couldn't replicate the error, could you post a complete example code?

**Comment by maikerlab** [comment]
Hello.
I was getting the same error and will try to give you more context.

Here is the stack trace:

```shell
echo: http: panic serving 127.0.0.1:55954: runtime error: invalid memory address or nil pointer dereference
goroutine 865 [running]:
net/http.(*conn).serve.func1()
	/Users/maik/.asdf/installs/golang/1.22.3/go/src/net/http/server.go:1898 +0xb0
panic({0x104d37940?, 0x1059a0430?})
	/Users/maik/.asdf/installs/golang/1.22.3/go/src/runtime/panic.go:770 +0x124
github.com/johnfercher/maroto/v2/pkg/components/col.(*Col).GetHeight(0x1400072a400, {0x104f21318, 0x14000164480}, 0x140007337b8)
	/Users/maik/Projects/marototest/vendor/github.com/johnfercher/maroto/v2/pkg/components/col/col.go:97 +0x80
github.com/johnfercher/maroto/v2/pkg/components/row.(*Row).getBiggestCol(0x140008ed348?, {0x104f21318, 0x14000164480}, 0x140007337b8)
	/Users/maik/Projects/marototest/vendor/github.com/johnfercher/maroto/v2/pkg/components/row/row.go:63 +0x74
github.com/johnfercher/maroto/v2/pkg/components/row.(*Row).GetHeight(0x1400072a2c0, {0x104f21318?, 0x14000164480?}, 0x1029ff7e0?)
	/Users/maik/Projects/marototest/vendor/github.com/johnfercher/maroto/v2/pkg/components/row/row.go:74 +0x34
github.com/johnfercher/maroto/v2.(*Maroto).getRowsHeight(...)
	/Users/maik/Projects/marototest/vendor/github.com/johnfercher/maroto/v2/maroto.go:378
github.com/johnfercher/maroto/v2.(*Maroto).RegisterHeader(0x14000733790, {0x14000ed8490, 0x1, 0x1})
	/Users/maik/Projects/marototest/vendor/github.com/johnfercher/maroto/v2/maroto.go:136 +0x68
github.com/johnfercher/maroto/v2.(*MetricsDecorator).RegisterHeader.func1()
	/Users/maik/Projects/marototest/vendor/github.com/johnfercher/maroto/v2/metricsdecorator.go:106 +0x40
github.com/johnfercher/maroto/v2/internal/time.GetTimeSpent(0x140008ed468)
	/Users/maik/Projects/marototest/vendor/github.com/johnfercher/maroto/v2/internal/time/time.go:12 +0x38
github.com/johnfercher/maroto/v2.(*MetricsDecorator).RegisterHeader(0x14000164510, {0x14000ed8490?, 0x28?, 0x140008ed580?})
	/Users/maik/Projects/marototest/vendor/github.com/johnfercher/maroto/v2/metricsdecorator.go:105 +0x5c
gitlab.com/maikerlab/marototest/pkg/backend.addHeader({0x104f1ba48, 0x14000164510}, {0x14000508860, 0x19}, {0x14000815f60, 0xe}, {0x1400082e060, 0x28}, {0x140003c3c10, 0xb})
```

And here is a snippet of my code:

```go
_ = m.RegisterHeader(
    row.New().Add(
        text.NewCol(6, "first col", props.Text{Size: 8.0, Align: align.Left}), 
	text.NewCol(6, "2nd col", props.Text{Size: 8.0, Align: align.Right}), 
    ),
)
```

**Comment by Fernando-hub527** [comment]
Hello!
Great!! I'll look into this error today, I think I can upload a correction today.

**Comment by Fernando-hub527** [comment]
Issue fixed, I believe it will be available soon.

![Captura de tela de 2024-09-16 17-01-28](https://github.com/user-attachments/assets/08336539-70df-413a-b2e4-28633a53ec63)

**Comment by maikerlab** [comment]
> Issue fixed, I believe it will be available soon.
> 
> ![Captura de tela de 2024-09-16 17-01-28](https://private-user-images.githubusercontent.com/66834579/367920146-08336539-70df-413a-b2e4-28633a53ec63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTk2NTYsIm5iZiI6MTcyNjU1OTM1NiwicGF0aCI6Ii82NjgzNDU3OS8zNjc5MjAxNDYtMDgzMzY1MzktNzBkZi00MTNhLWIyZTQtMjg2MzNhNTNlYzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA3NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNzc2YWJhYTg0ZmE3NjZkMzY1ODU5ZmQ5OGE2ZDg3ZDc4ZTRiMmQ0MWRlZjU0ZjE3Yzk1M2I4ODNiMzNiNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tYVXY3UhQe_yC6GhhxrObdF9JEPy-fyo1QRQg0KUAjs)

Great, wow that was fast! Thanks! :)

**Comment by johnfercher** [comment]
This problem should be solved in this new release (https://github.com/johnfercher/maroto/releases/tag/v2.1.3), I will close this issue. If it reapers, we can re-open the issue.
