### ISSUE TITLE
qr-code scans to "no usable data found"

### ISSUE THREAD

**Issue by ChrisHuston** [johnfercher/maroto#476]
**Describe the bug**
When adding a qr-code to a pdf, the generated qr-code results in "no usable data found" when scanned.

**To Reproduce**
1. m := maroto.New()
2. 	m.AddRow(80,
		code.NewQrCol(12, "https://go.dev/", props.Rect{
			Center:  true,
			Percent: 100,
		}),
	)
3. scan generated qr-code
4. scanned code shows: "no usable data found"

**Related code:**
provider.go line 80
img, err := g.loadCode(fmt.Sprintf("qr-code-%s", code), g.code.GenQr)
changing this line to:
img, err := g.loadCode(code, g.code.GenQr)
results in a qr-code that scans correctly

**Expected behavior**
Scanned qr-code will display web page

**Comment by Fernando-hub527** [comment]
Hello
Bug fixed, I believe it will be available soon

**Comment by johnfercher** [comment]
Fixed in https://github.com/johnfercher/maroto/releases/tag/v2.1.4
