### ISSUE TITLE
Metadata such as title, author, creator not set

### ISSUE THREAD

**Issue by vljukap98** [johnfercher/maroto#485]
**Describe the bug**
When creating the configuration with the Builder provided in the config package and using it to add title, author, creator, subject and creation date to the document in combination with concurrent mode and sequential low memory mode, output pdf doesn't contain set metadata. When I don't use the concurrent mode or sequential low memory mode, all above is set except for the creation date (I've not managed to set creation date in any way). 

**To Reproduce**
1. Run the code provided below (Related code section)
2. Open test.pdf with any viewer (e.g. I used Mozilla's Firefox)
3. Open properties
4. Properties set (author, creator, subject, title) are empty

**Related code:**
```
func main() {
	m := getMaroto()
	document, err := m.Generate()
	if err != nil {
		log.Fatal(err.Error())
	}
	err = document.Save("test.pdf")
	if err != nil {
		log.Fatal(err.Error())
	}
}

func getMaroto() core.Maroto {
	cfg := config.NewBuilder().
		WithConcurrentMode(7).
		WithSequentialLowMemoryMode(7).
		WithTitle("custom_title", false).
		WithAuthor("custom_author", false).
		WithCreator("custom_creator", false).
		WithSubject("custom_subject", false).
		WithCreationDate(time.Now()).
		Build()

	mrt := maroto.New(cfg)
	m := maroto.NewMetricsDecorator(mrt)

	m.AddRows(
		text.NewRow(30, "metadatas"),
	)

	return m
}
```

**Expected behavior**
Properties should contain set data. I managed to set it without using `WithConcurrentMode(7)` and `WithSequentialLowMemoryMode(7)`.
![image](https://github.com/user-attachments/assets/63938369-835e-465b-8715-e5def260f5fe)
Still creation date remains empty.

**Stacktrace**
-

**Additional details (please complete the following information):**
 - OS: Ubuntu 24.04.1
 - Maroto version 2.1.5

**Additional context**

**Comment by Fernando-hub527** [comment]
Hello!
PR has been opened. I believe a fix will be available soon !!
