### ISSUE TITLE
Is there a way to Generate a PDF/A-3 with an XML File ?

### ISSUE THREAD

**Issue by GattusoGregory** [johnfercher/maroto#491]
**Is your feature request related to a problem? Please describe.**
For the french invoicing system, i need to create invoice in factur-X format. For this i need a PDF/A-3 format and add an XML inside

**Describe the solution you'd like**
Can choose the PDF Format and add a file inside

**Comment by Fernando-hub527** [comment]
Hello, sorry for the delay. I did some research to find out if it is possible to implement this feature, but considering that Maroto uses gofpdf as a provider and gofpdf does not support PDF/A-3 format, unfortunately it is not possible to implement this feature at the moment.

**Comment by Fernando-hub527** [comment]
I'm going to close this issue, but if you have any questions or ideas for adding this feature, feel free to reopen it.
