### ISSUE TITLE
Markdown/HTML support

### ISSUE THREAD

**Issue by cocoza4** [johnfercher/maroto#497]
Is there any plan to support markdown/HTML format?

**Comment by Fernando-hub527** [comment]
Hello, we are working on a document process that will allow you to generate PDFs from different types of documents. At first, this feature will only support JSON, but we plan to add HTML support in the future.
If you want to learn more about the feature or make a contribution: https://github.com/johnfercher/maroto/discussions/390

**Comment by cocoza4** [comment]
thank you for your response
