### ISSUE TITLE
QrCode example

### ISSUE THREAD

**Issue by johnferchermeli** [johnfercher/maroto#51]
**Maroto version:**
Latest

**I'm submitting a ...** 

- [ ] bug report
- [x] documentation request
- [ ] feature request

**Other information:**

* There is no example of how to use QrCode, we must add one in pkg/pdf/example_test.go

**Comment by stanleynguyen** [comment]
Hi @johnfercher @johnferchermeli Can I take up this issue?

**Comment by johnfercher** [comment]
Hi @stanleynguyen, of course. I think you could follow this example:
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/example_test.go#L105-L129

**Comment by johnfercher** [comment]
Done :D
