### ISSUE TITLE
Refactor Row

### ISSUE THREAD

**Issue by johnferchermeli** [johnfercher/maroto#55]
**Maroto version:**
Latest

**I'm submitting a ...** 

- [ ] bug report
- [x] refactor proposal
- [ ] documentation request
- [ ] feature request

**Current behavior:**
The Row method from PdfMaroto is couple between footer height calculation, footer and header execution and default execution.

**Expected behavior:**
We must improve the code in this part.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L212-L240

**Comment by johnfercher** [comment]
This feature is already implemented in V2. Please refer to [improve usability](https://maroto.io/#/README?id=improve-usability) to use it. I will keep this issue alive until V2 reaches a stable version.
