### ISSUE TITLE
Improve testability

### ISSUE THREAD

**Issue by johnferchermeli** [johnfercher/maroto#56]
**Maroto version:**
Latest

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request

**Current behavior:**
Nowadays the users must use some lib like Mockery to mock the maroto behavior. The problem is that the automatic methods doesn't provide support to recursive assertions, and this limits the development.

**Expected behavior:**
Maroto must provide a mock which allow the assertion of method inside a closure.

**Comment by johnfercher** [comment]
This feature is already implemented in V2. Please refer to [unit-testing](https://maroto.io/#/v2/tests?id=unit-testing) to use it. I will keep this issue alive until V2 reaches a stable version.
