### ISSUE TITLE
Cannot define an uncentralized FileImage

### ISSUE THREAD

**Issue by johnfercher** [johnfercher/maroto#57]
**Maroto version:**
Latest

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
There is no implementation of uncentralized FileImage.

**Expected behavior:**
We should have uncentralized FileImage.

**Steps to reproduce:**
If you pass a *prop* forcing uncentralized , it will centralize the barcode anyway.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L300-L304

**Comment by SuddenGunter** [comment]
what do you mean by 'uncentralized'?
where it should be then?
left/right aligned?

**Comment by johnfercher** [comment]
It should be left aligned and the user must past the top and left properties.

**Comment by SuddenGunter** [comment]
@johnfercher may I take it?
Seems as simple fix. In debugger I've found where is the place when you calculate center coordinates - just need to add 'if' statement and pass user's coordinates if not centered. See example with non-centered image:
![1571079666_2201_14102019_1063x624](https://user-images.githubusercontent.com/15653599/66776104-4f24db80-eece-11e9-88b5-b51228e3fb28.png)
Only thing that keeps me from uploading PR right now - is that this method already has 7 params and introduce more for "top/left coordinates that passed if image is not centered" makes API even more difficult to understand.
Will try to get around

**Comment by johnfercher** [comment]
Very nice. This issue of the 7 parameters is something to care about, but actually, this API is no used by the "users/programmers", this is only a helper which the maroto api uses. However, I saw that you are passing the **props.Rect** instead of more two parameters, this is very good. 

I will have a look at your code 👍
