### ISSUE TITLE
Cannot define an uncentralized Base64Image

### ISSUE THREAD

**Issue by johnfercher** [johnfercher/maroto#58]
**Maroto version:**
Latest

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
There is no implementation of uncentralized Base64Image.

**Expected behavior:**
We should have uncentralized Base64Image.

**Steps to reproduce:**
If you pass a *prop* forcing uncentralized , it will centralize the barcode anyway.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L320-L324

**Comment by SuddenGunter** [comment]
actually I believe it would be fixed in https://github.com/johnfercher/maroto/pull/90
https://github.com/johnfercher/maroto/pull/90/files#diff-5a76e7d6bb75c76f9c76683b3e2daf0fL381

**Comment by johnfercher** [comment]
It will not. But to resolve this issue is just follow what was done in #90.

**Comment by johnfercher** [comment]
Yes, it will :D
