### ISSUE TITLE
Cannot define an uncentralized QrCode

### ISSUE THREAD

**Issue by johnfercher** [johnfercher/maroto#60]
**Maroto version:**
Latest

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request

**Current behavior:**
There is no implementation of uncentralized QrCode..

**Expected behavior:**
We should have uncentralized QrCode.

**Steps to reproduce:**
If you pass a *prop* forcing uncentralized, it will centralize the barcode anyway.

**Related code:**
https://github.com/johnfercher/maroto/blob/51bcd1b9a20143cb70ccb295151d863854b93f79/pkg/pdf/pdf.go#L373-L377

**Comment by SuddenGunter** [comment]
@johnfercher 
pls see this https://github.com/johnfercher/maroto/blob/52b291471d9a30383b4f4ae640b32c0444778b72/internal/code.go#L37
is it correct that AddBar and AddQr end with barcode.Barcode??

**Comment by johnfercher** [comment]
@SuddenGunter, is correct.

**Comment by johnfercher** [comment]
fixed in #104
