### ISSUE TITLE
Update issue templates

### ISSUE THREAD

**Issue by johnferchermeli** [johnfercher/maroto#61]
**Maroto version:**
Latest

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request
- [x] config request

**Current behavior:**
The current issue_template.md is the old version.

**Expected behavior:**
The project should update to the new version.

**Comment by soulspark666** [comment]
What kind of Issue template do you want instead of issue_template.MD???
- Bug Report
- Feature Request
- Custom Template

**Comment by soulspark666** [comment]
On examining the pull_request_template.md file, I did not find any warnings stating that `old version` is being used, like what I found in `issue_template.md`.

**Comment by soulspark666** [comment]
In which branch should I merge my PR?

**Comment by johnfercher** [comment]
Hi, I think that **bug report** and **feature request** would be greater. You can create your PR to dev branch.
