### ISSUE TITLE
Add RegisterFooter to diagram image 

### ISSUE THREAD

**Issue by johnfercher** [johnfercher/maroto#75]
**Maroto version:**

**I'm submitting a ...** 

- [ ] bug report
- [ ] refactor proposal
- [x] documentation request
- [ ] config proposal
- [ ] feature request

**Current behavior:** 
The current diagram Image doesn't have a RegisterFooter at same level as RegisterHeader.

**Expected behavior:** 
We should add to the diagram to show that is possible use a RegisterFooter like the RegisterHeader.

**Related code:** 
https://github.com/johnfercher/maroto/blob/master/internal/assets/images/diagram.png

**Other information:**
The current Image was generated with https://www.draw.io/?libs=general

**Comment by kazuhirodk** [comment]
I'll work on this right now

**Comment by johnfercher** [comment]
Hey, merged :D. Thanks
