### ISSUE TITLE
Add Star charts to README.md

### ISSUE THREAD

**Issue by johnfercher** [johnfercher/maroto#76]
**I'm submitting a ...** 

- [ ] bug report
- [ ] refactor proposal
- [ ] documentation request
- [x] config proposal
- [ ] feature request

**Current behavior:** 
There is no star chart in README.md like https://github.com/goreleaser/goreleaser

**Expected behavior:** 
We should add this star chart.

**Related code:** 
https://starchart.cc/johnfercher/maroto

**Comment by Pensu** [comment]
@johnfercher I would like to take this one, if it's available.

**Comment by johnfercher** [comment]
Hey, it's available.
