### ISSUE TITLE
All 3 examples broken (panic: runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by marco-m** [johnfercher/maroto#98]
Hello,

the 3 examples expect to be run from the root directory of the maroto repository. If they are run in another directory, they crash.

For example:

```
$ pwd
maroto/bin

$ ./sample1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb0 pc=0x11d4d5d]
goroutine 1 [running]:
github.com/jung-kurt/gofpdf.(*ImageInfoType).Width(...)
	/Users/mmolteni/sync/src/go/pkg/mod/github.com/jung-kurt/gofpdf@v1.4.2/def.go:248
...
```

The simplest possible fix is not to ignore errors :-). For example:

```
 func main() {
    m := pdf.NewMaroto(consts.Portrait, consts.A4)
    //m.SetBorder(true)

-   byteSlices, _ := ioutil.ReadFile("internal/assets/images/biplane.jpg")
+   byteSlices, err := ioutil.ReadFile("internal/assets/images/biplane.jpg")
+   if err != nil {
+       fmt.Println("Got error while opening file:", err)
+       os.Exit(1)
+   }
```

**Comment by johnfercher** [comment]
Hi, I would like to have these samples inside the maroto project. They shouldn't be installed. However, I will add this treatment.

**Comment by marco-m** [comment]
> Hi, I would like to have these samples inside the maroto project.

I understand. My point is not that they should work everywhere, it is that they should gracefully terminate instead than crashing :-)

**Comment by johnfercher** [comment]
Yes, of course. Thank you very much :D

**Comment by johnferchermeli** [comment]
Fixing in #102

**Comment by johnfercher** [comment]
Fixed
