### ISSUE TITLE
FileImage() and other I/O functions should handle errors

### ISSUE THREAD

**Issue by marco-m** [johnfercher/maroto#99]
Hello,

Maroto has a certain number of functions that wrap I/O operations, such as FileImage(filePathName string, prop ...props.Rect), that do not return an error.

If an error happens (simplest example: the path doesn't exist), Maroto internal state will sooner or later cause a crash (see for example #98).

I understand that gofpdf "delays" errors, but it does so in a way to keep the internal state crash-proof. Maroto should do the same.

thanks!

**Comment by johnfercher** [comment]
Hi, this totally make sense. I will create an item to solve this :D

**Comment by marco-m** [comment]
Thanks for the quick reaction John!

**Comment by johnferchermeli** [comment]
Fixing in #102

**Comment by johnfercher** [comment]
Fixed
